---
- hosts: base.local
#  become: yes
  vars_files:
  - ~/repos/toolbox/playbook/lxc/lxc-target.yml
  tasks: 
  - name: "create lxc dir"
    file:
      path: ~/.config/lxc
      state: directory
      mode: 0755
  - name: "create lxc config file"
    shell: cp -f /etc/lxc/default.conf ~/.config/lxc/default.conf
  - name: "add lxc idmap"
    shell: sh -c 'echo  "lxc.include = /etc/lxc/default.conf\nlxc.id_map = u 0 100000 65536\nlxc.id_map = g 0 100000 65536" >> ~/.config/lxc/default.conf'
  - name: "create container"
    lxc_container:
#      name: test1
      name: "{{ item.vm }}"
      container_log: true
#      lxc_path: /var/lib/lxc
      template: download
      template_options:
        --dist {{ lxc_container_map_distro }}
        --release {{ lxc_container_map_release }}
        --arch {{ lxc_container_map_arch }}
      state: started
    with_items: "{{ vms }}"
  - name: "apt update"
    shell: lxc-attach -n {{ item.vm }} -- su -c "apt-get update"
    with_items: "{{ vms }}"
  - name: "inatall avahi-daemon ssh"
    shell: lxc-attach -n {{ item.vm }} -- su -c "apt-get install -y avahi-daemon ssh && systemctl stop avahi-daemon.service"
    with_items: "{{ vms }}"
  - name: "set param avahi_config"
    shell: lxc-attach -n {{ item.vm }} -- su -c 'sed -ie 's/rlimit-nproc=3/rlimit-nproc=256/g' /etc/avahi/avahi-daemon.conf'
    with_items: "{{ vms }}"
  - name: "set param sshd_config"
    shell: lxc-attach -n {{ item.vm }} -- su -c 'echo -e "PermitRootLogin yes\nPasswordAuthentication yes\nPermitEmptyPasswords no" >> /etc/ssh/sshd_config'
    with_items: "{{ vms }}"
  - name: "set root password"
    shell: lxc-attach -n {{ item.vm }} -- su -c 'echo -e "root:debian" | chpasswd'
    with_items: "{{ vms }}"
  - name: "restart and enable avahi-daemon sshd"
    shell: lxc-attach -n {{ item.vm }} -- su -c "systemctl restart avahi-daemon.service && systemctl enable avahi-daemon.service && systemctl restart ssh.service && systemctl enable ssh.service"
    with_items: "{{ vms }}"
