---
- hosts: base.local
  vars_files:
  - ~/repos/toolbox/playbook/lxc/lxc-target.yml
  tasks: 
  - name: stop container and destroy
    lxc_container:
      name: "{{ item.vm }}"
      state: stopped
    with_items: "{{ vms }}"
  - name: Destroy a container
    lxc_container:
      name: "{{ item.vm }}"
      state: absent
    with_items: "{{ vms }}"
